#
# Copyright (C) 2022 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
- name: Install gProfiler
  hosts: all
  vars:
    gprofiler_path: /tmp/gprofiler
    # can be overriden to add extra arguments to gProfiler's execution, such as --no-perf.
    gprofiler_args: ""
  tasks:
    - name: Check mandatory variables
      assert:
        that:
          - gprofiler_path is defined
          - gprofiler_token is defined
          - gprofiler_service is defined
          - gprofiler_args is defined
    - name: Get remote machine architecture
      shell: uname -m
      register: machine
    - name: Download latest gProfiler
      ansible.builtin.get_url:
        url: https://github.com/Granulate/gprofiler/releases/latest/download/gprofiler_{{machine.stdout}}
        dest: "{{gprofiler_path}}"
        mode: '0755'
        owner: root
        group: root
      become: true
    - name: Run gProfiler
      shell: TMPDIR=$(dirname {{gprofiler_path}}) setsid {{gprofiler_path}} -cu --token="{{gprofiler_token | mandatory}}" --service-name="{{gprofiler_service | mandatory}}" {{gprofiler_args}} > /dev/null 2>&1 &
      become: true
