name: granulate-utils lint

on: pull_request

jobs:
  lint:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: Run linters
      run: ./lint.sh --ci
