version: "3.9"

services:
  gprofiler:
    image: granulate/gprofiler:latest
    restart: always
    container_name: "granulate-gprofiler"
    pid: "host"
    userns_mode: "host"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro

    command: '-cu --token "<TOKEN>" --service-name "<SERVICE NAME>"'
