name: Build gProfiler on Windows

on: pull_request
# on:
#   pull_request:
#   push:
#     tags:
#       - 'windows'

jobs:
  build-executable:
   runs-on: windows-latest
   steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: where am i
        run: pwd

      - name: what is there
        run: dir

      - name: install chocolatey
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      
      - name: install wget
        run: choco install wget -y

      - name: python?
        run: python3 --version
        
      - name: run the build script
        run: .\scripts\windows\build.bat

      - name: run the build script again?
        run: .\scripts\windows\build.bat

      - name: remove app dir
        run: rmdir -r .\app -force
        shell: cmd

      - name: remove dep dir
        run: rmdir -r .\dep -force
        shell: cmd  