name: Build gProfiler on Windows

on: pull_request
# on:
#   pull_request:
#   push:
#     tags:
#       - 'windows'

jobs:
  build-executable:
   runs-on: windows-latest
   steps:
      - name: run the build script
        run: .\scripts\windows\build.bat

      - name: remove app dir
        run: rmdir -r .\app -force

      - name: remove dep dir
        run: rmdir -r .\dep -force