name: Build gProfiler on Windows

on: pull_request
# on:
#   pull_request:
#   push:
#     tags:
#       - 'windows'

jobs:
  build-executable:
   runs-on: windows-latest
   steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: install chocolatey
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      
      - name: install wget
        run: choco install wget -y
        
      - name: run the build script
        run: .\scripts\windows\build.bat

      - name: check gprofiler build
        run: .\app\dist\gprofiler.exe -h