apiVersion: v1
kind: Namespace
metadata:
  name: granulate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: granulate-service-account
  namespace: granulate
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-privileged
  namespace: granulate
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
    verbs:
      - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-privileged
subjects:
  - kind: ServiceAccount
    name: granulate-service-account
roleRef:
  kind: Role
  name: use-privileged
  apiGroup: rbac.authorization.k8s.io
